layout_spectrum: 0
typography_spectrum: 0.8340425
color:
  saturation: 0.3072473
  lightness: 0.9543211
  brandStrength: 0.4042553
  brandColors:
    - '#200B0B'
    - '#D7B5A1'
    - '#6E4A43'
    - '#C6782E'
    - '#5C2715'
  rhythmicContrast: 0.1119474
name: mrconnolly
