name: mrconnolly
favicon: null
layout_spectrum: 0.85095
typography_spectrum: 0.89958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee0df'
    - '#160400'
    - '#c0baa8'
    - '#4f5559'
    - '#b3633f'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
